// generate.js — Run ONCE to create your Ed25519 key pair and write .env
// After this, the keys/ folder is not needed — everything runs from .env
// Usage: node generate.js

const nacl = require("tweetnacl");
const util = require("tweetnacl-util");
const fs = require("fs");
const path = require("path");

const keyPair = nacl.sign.keyPair();

const pubB64 = util.encodeBase64(keyPair.publicKey);
const privB64 = util.encodeBase64(keyPair.secretKey);

const envContent = `# Auto-generated by generate.js — DO NOT commit to git
PORT=4000
PUBLIC_KEY_B64=${pubB64}
PRIVATE_KEY_B64=${privB64}
`;

fs.writeFileSync(path.join(__dirname, ".env"), envContent, "utf8");

console.log("✅ .env written with fresh Ed25519 key pair.");
console.log("⚠️  .env is in .gitignore — never commit the private key!");
console.log(`   Public key (base64): ${pubB64.slice(0, 20)}...`);
