require("dotenv").config();

const nacl = require("tweetnacl");
const util = require("tweetnacl-util");

// ─── Key Storage ──────────────────────────────────────────────────────────
// Keys are read exclusively from process.env (loaded from .env).
// Production: set these as environment variables in your Vault/KMS/CI.
// Local: generated by running `node generate.js` once.
// ─────────────────────────────────────────────────────────────────────────

function loadKeys() {
  const pub = process.env.PUBLIC_KEY_B64;
  const priv = process.env.PRIVATE_KEY_B64;

  if (!pub || !priv) {
    throw new Error(
      "❌  PUBLIC_KEY_B64 or PRIVATE_KEY_B64 missing from environment.\n" +
      "   Run `node generate.js` to create your .env file first."
    );
  }

  return {
    publicKey: util.decodeBase64(pub),
    privateKey: util.decodeBase64(priv),
  };
}

// JWK spec requires base64url (RFC 4648 §5): no +, no /, no = padding
function toBase64Url(bytes) {
  return Buffer.from(bytes)
    .toString("base64")
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=/g, "");
}

// Returns the Ed25519 public key as a JSON Web Key (JWK) object.
function getPublicKeyJwk() {
  const { publicKey } = loadKeys();
  return {
    kty: "OKP",
    crv: "Ed25519",
    x: toBase64Url(publicKey),
  };
}

function generateKeys() {
  return nacl.sign.keyPair();
}

function sign(data) {
  const { privateKey } = loadKeys();
  const message = util.decodeUTF8(JSON.stringify(data));
  const signature = nacl.sign.detached(message, privateKey);
  return util.encodeBase64(signature);
}

function verify(data, signature, publicKey) {
  const message = util.decodeUTF8(JSON.stringify(data));
  const sig = util.decodeBase64(signature);
  return nacl.sign.detached.verify(message, sig, publicKey);
}

module.exports = {
  generateKeys,
  loadKeys,
  sign,
  verify,
  getPublicKeyJwk,
};
